"""
General description:
Reads the exact daily equity curve generated by the portfolio backtester, 
fetches the S&P 500 (SPY) baseline via Yahoo Finance, and plots a comparative 
performance graph using Matplotlib for the research paper.
"""

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import os

INPUT_FILE = "Data/optimal_equity_curve.csv"
OUTPUT_IMG = "Data/Figure_2_Equity_Curve.png"

def main():
    if not os.path.exists(INPUT_FILE):
        print("❌ Error: Run portfolio_backtest.py first to generate the equity curve.")
        return
        
    # 1. Load the exact data generated by your backtester
    print("📦 Loading backtest history...")
    df = pd.read_csv(INPUT_FILE, parse_dates=['Date'])
    df.set_index('Date', inplace=True)
    
    first_date = df.index.min()
    last_date = df.index.max()
    starting_capital = df['Strategy_Equity'].iloc[0]
    
    # 2. Fetch the S&P 500 baseline
    print(f"📈 Fetching SPY Benchmark from {first_date.date()} to {last_date.date()}...")
    spy = yf.download('SPY', start=first_date, end=last_date)['Close']
    
    if isinstance(spy, pd.DataFrame): # Handle yfinance formatting updates
        spy = spy.iloc[:, 0]
        
    # Normalize SPY to start at your exact starting capital ($100,000)
    spy_normalized = (spy / spy.iloc[0]) * starting_capital
    df = df.join(spy_normalized.rename('SPY_Equity'), how='left').ffill()

    # 3. Generate the Graph
    print("🎨 Generating Institutional Tear Sheet Graph...")
    plt.style.use('dark_background')
    fig, ax = plt.subplots(figsize=(12, 6))

    ax.plot(df.index, df['Strategy_Equity'], color='#00ff99', linewidth=2, label='AI Strategy (Optimal Threshold)')
    ax.plot(df.index, df['SPY_Equity'], color='#aaaaaa', linewidth=1.5, linestyle='--', label='S&P 500 (SPY Benchmark)')

    # Formatting
    ax.set_title("Autonomous Strategy vs S&P 500 (2020-2025 Stress Test)", fontsize=16, fontweight='bold', pad=15)
    ax.set_ylabel("Portfolio Value ($)", fontsize=12)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))
    
    # Date formatting
    ax.xaxis.set_major_locator(mdates.YearLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    
    ax.grid(color='#333333', linestyle='--', alpha=0.5)
    ax.legend(loc='upper left', fontsize=12)

    plt.tight_layout()
    plt.savefig(OUTPUT_IMG, dpi=300)
    print(f"✅ SUCCESS! Graph saved to {OUTPUT_IMG}")
    
    # Calculate Final Stats
    strat_return = (df['Strategy_Equity'].iloc[-1] / starting_capital - 1) * 100
    spy_return = (df['SPY_Equity'].iloc[-1] / starting_capital - 1) * 100
    print("-" * 40)
    print(f"📊 Final Strategy Return: +{strat_return:,.2f}%")
    print(f"📊 Final S&P 500 Return:  +{spy_return:,.2f}%")
    print("-" * 40)

if __name__ == "__main__":
    main()